# Generated by Django 4.2.4 on 2024-05-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainees', models.ManyToManyField(related_name='diet_plans', to='api.gymuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='api.gymtrainer')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day_1', 'Day 1'), ('day_2', 'Day 2'), ('day_3', 'Day 3'), ('day_4', 'Day 4'), ('day_5', 'Day 5'), ('day_6', 'Day 6'), ('day_7', 'Day 7')], max_length=10)),
                ('breakfast', models.TextField(blank=True, null=True)),
                ('lunch', models.TextField(blank=True, null=True)),
                ('dinner', models.TextField(blank=True, null=True)),
                ('snacks', models.TextField(blank=True, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.dietplan')),
            ],
            options={
                'unique_together': {('diet_plan', 'day')},
            },
        ),
    ]
