# Generated by Django 4.2.4 on 2024-06-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dietplan_dietplanday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainees', models.ManyToManyField(related_name='workout_plans', to='api.gymuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='api.gymtrainer')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='gym',
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(choices=[('day_1', 'Day 1'), ('day_2', 'Day 2'), ('day_3', 'Day 3'), ('day_4', 'Day 4'), ('day_5', 'Day 5'), ('day_6', 'Day 6'), ('day_7', 'Day 7')], max_length=10)),
                ('exercises', models.ManyToManyField(related_name='workout_plan_day', to='api.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.workoutplan')),
            ],
            options={
                'unique_together': {('workout_plan', 'day')},
            },
        ),
    ]
