# Generated by Django 4.2.4 on 2024-06-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutplan_remove_exercise_gym_workoutplanday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplanday',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plan_exercises', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutplanday',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workout_plan_days', to='api.workoutplan'),
        ),
    ]
